services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: energy-todo
    image: ghcr.io/mgrimace/energy-todo:latest
    ports:
      - "3000:3000"
    volumes:
      - ./energy-data:/app/data:rw
    restart: unless-stopped