import type { ThemeDefinition } from './types'

export const catpuccinTheme: ThemeDefinition = {
  id: 'catppuccin',
  name: 'Catppuccin',
  palettes: {
    light: {
      bg: '#EFF1F5',
      surface: '#E6E9EF',
      surfaceAlt: '#DCE0E8',
      hover: '#E6E9EF',
      text: '#4C4F69',
      textMuted: '#6C6F85',
      accent: '#1E66F5',
      accentStrong: '#7287FD',
      accentOn: '#EFF1F5',
      focus: '#04A5E5',
      border: '#BCC0CC',
      borderStrong: '#ACB0BE',
      success: '#40A02B',
      danger: '#D20F39',
      warning: '#DF8E1D',
      dangerSoft: '#DCE0E8',
      toggleTrack: '#BCC0CC',
      energyLowBg: '#DCE0E8',
      energyLowBorder: '#40A02B',
      energyLowText: '#4C4F69',
      energyMediumBg: '#DCE0E8',
      energyMediumBorder: '#1E66F5',
      energyMediumText: '#4C4F69',
      energyHighBg: '#DCE0E8',
      energyHighBorder: '#8839EF',
      energyHighText: '#4C4F69'
    },
    dark: {
      bg: '#1E1E2E',
      surface: '#181825',
      surfaceAlt: '#11111B',
      hover: '#313244',
      text: '#CDD6F4',
      textMuted: '#A6ADC8',
      accent: '#89B4FA',
      accentStrong: '#B4BEFE',
      accentOn: '#1E1E2E',
      focus: '#89DCEB',
      border: '#45475A',
      borderStrong: '#585B70',
      success: '#A6E3A1',
      danger: '#F38BA8',
      warning: '#F9E2AF',
      dangerSoft: '#313244',
      toggleTrack: '#585B70',
      energyLowBg: '#313244',
      energyLowBorder: '#A6E3A1',
      energyLowText: '#CDD6F4',
      energyMediumBg: '#313244',
      energyMediumBorder: '#89B4FA',
      energyMediumText: '#CDD6F4',
      energyHighBg: '#313244',
      energyHighBorder: '#CBA6F7',
      energyHighText: '#CDD6F4'
    }
  }
}
